import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import { FileText, Download, Lock, Check, CreditCard, Loader2, ShieldCheck, X } from 'lucide-react';
import { Vehicle } from '../types';

interface Props {
  vehicle: Vehicle;
}

const Report: React.FC<Props> = ({ vehicle }) => {
  const [hasPaid, setHasPaid] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [showPayment, setShowPayment] = useState(false);

  // Mock payment processing
  const handlePayment = () => {
    setIsProcessing(true);
    // Simulate API latency
    setTimeout(() => {
      setIsProcessing(false);
      setHasPaid(true);
      setShowPayment(false);
    }, 2000);
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const vStr = vehicle.make ? `${vehicle.year} ${vehicle.make} ${vehicle.model}` : 'Unknown Vehicle';
    const dateStr = new Date().toLocaleDateString();
    
    // Header
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Vehicle Health Report", 20, 25);
    doc.setFontSize(10);
    doc.text("Generated by Fuse Finder Pro", 150, 25);

    // Vehicle Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Vehicle Information", 20, 60);
    doc.line(20, 62, 190, 62);
    
    doc.setFontSize(12);
    doc.text(`Vehicle: ${vStr}`, 20, 75);
    doc.text(`Date: ${dateStr}`, 20, 85);
    doc.text(`Report ID: #${Math.floor(Math.random() * 100000)}`, 140, 75);

    // Diagnostics Summary Placeholder
    doc.setFontSize(14);
    doc.text("Diagnostics Summary", 20, 110);
    doc.line(20, 112, 190, 112);
    
    doc.setFontSize(11);
    doc.text("• Fuse System: No active faults detected in lookup history.", 25, 125);
    doc.text("• Maintenance: Schedule generated based on mileage.", 25, 135);
    doc.text("• Visual Inspection: Tire and Oil analysis data included.", 25, 145);

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is generated by AI based on user inputs. Consult a professional mechanic.", 20, 280);

    doc.save("vehicle-health-report.pdf");
  };

  if (!vehicle.make) {
    return (
        <div className="flex flex-col items-center justify-center py-20 text-center px-4">
            <div className="bg-slate-100 p-6 rounded-full mb-4">
                <FileText className="h-10 w-10 text-slate-400" />
            </div>
            <h2 className="text-xl font-bold text-slate-700">No Vehicle Selected</h2>
            <p className="text-slate-500 mt-2 max-w-sm">Please return Home to select a vehicle before generating a report.</p>
        </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      {/* Header */}
      <div className="text-center mb-10">
         <h1 className="text-3xl font-bold text-slate-900">Vehicle Health Report</h1>
         <p className="text-slate-600 mt-2 max-w-2xl mx-auto">
            Comprehensive diagnostics, maintenance schedules, and system analysis for your <strong>{vehicle.year} {vehicle.make} {vehicle.model}</strong>.
         </p>
      </div>

      <div className="grid md:grid-cols-2 gap-8 items-stretch">
        {/* Preview / Benefits Column */}
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 flex flex-col">
           <h2 className="font-bold text-xl mb-6 flex items-center gap-2 text-slate-800">
             <FileText className="h-6 w-6 text-blue-600" /> What's Included
           </h2>
           <ul className="space-y-4 flex-grow">
             <ListItem text="Tire Health Analysis & Tread Life Estimate" />
             <ListItem text="Engine Oil Condition Assessment" />
             <ListItem text="Dashboard Warning Light History" />
             <ListItem text="OEM Recommended Maintenance Schedule" />
             <ListItem text="Fuse Box Diagrams & Location Data" />
           </ul>
           
           <div className="mt-8 bg-slate-50 p-4 rounded-xl border border-slate-200 flex items-center gap-4">
               <div className="bg-white p-3 rounded-lg shadow-sm border border-slate-100">
                  <div className="text-red-500 font-bold text-[10px] leading-none mb-1">PDF</div>
                  <FileText className="h-8 w-8 text-slate-700" />
               </div>
               <div>
                  <p className="font-bold text-slate-800 text-sm">Full_Diagnostic_Report.pdf</p>
                  <p className="text-xs text-slate-500">Includes high-res images & charts</p>
               </div>
           </div>
        </div>

        {/* Payment / Action Column */}
        <div className="bg-white p-8 rounded-2xl shadow-lg border border-blue-100 relative overflow-hidden flex flex-col justify-center">
           {!hasPaid ? (
             <div className="text-center">
                <div className="bg-blue-50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 ring-4 ring-blue-50/50">
                   <Lock className="h-10 w-10 text-blue-600" />
                </div>
                <h3 className="text-2xl font-bold text-slate-900 mb-3">Unlock Premium Report</h3>
                <p className="text-slate-600 mb-8 text-sm leading-relaxed px-4">
                  Get a professional-grade PDF report of your vehicle's status to share with your mechanic or keep for your records.
                </p>
                
                <div className="mb-8 flex justify-center items-baseline gap-1">
                  <span className="text-5xl font-extrabold text-slate-900">$1</span>
                  <span className="text-slate-500 font-medium">.00</span>
                </div>

                <button 
                  onClick={() => setShowPayment(true)}
                  className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-xl transition-all shadow-lg hover:shadow-blue-500/25 flex items-center justify-center gap-2 group"
                >
                  Upgrade & Download
                  <Lock className="h-4 w-4 opacity-80 group-hover:hidden" />
                  <Check className="h-4 w-4 hidden group-hover:block" />
                </button>
                <p className="mt-4 text-[11px] text-slate-400 flex items-center justify-center gap-1">
                  <ShieldCheck className="h-3 w-3" /> Secure Payment via Stripe (Mock)
                </p>
             </div>
           ) : (
             <div className="text-center animate-fade-in h-full flex flex-col justify-center">
                <div className="bg-green-50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 border border-green-100">
                   <Check className="h-10 w-10 text-green-600" />
                </div>
                <h3 className="text-2xl font-bold text-slate-900 mb-2">Payment Successful!</h3>
                <p className="text-slate-600 mb-8 text-sm">
                  Your report is ready. Thank you for your purchase.
                </p>
                
                <button 
                  onClick={generatePDF}
                  className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-4 rounded-xl transition shadow-lg flex items-center justify-center gap-2"
                >
                  <Download className="h-5 w-5" />
                  Download PDF Now
                </button>
             </div>
           )}
        </div>
      </div>

      {/* Mock Payment Modal */}
      {showPayment && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-fade-in">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden transform transition-all scale-100">
            <div className="p-5 border-b border-slate-100 flex justify-between items-center bg-slate-50">
               <h3 className="font-bold text-slate-800 flex items-center gap-2">
                 <ShieldCheck className="h-5 w-5 text-green-600" /> Secure Checkout
               </h3>
               <button onClick={() => setShowPayment(false)} className="text-slate-400 hover:text-slate-600 p-1 rounded-full hover:bg-slate-200 transition">
                 <X className="h-5 w-5" />
               </button>
            </div>
            
            <div className="p-6 space-y-5">
              <div className="flex items-center justify-between p-4 bg-blue-50/50 rounded-xl border border-blue-100">
                 <div className="flex items-center gap-3">
                    <div className="bg-blue-100 p-2 rounded-lg">
                       <FileText className="h-5 w-5 text-blue-600" />
                    </div>
                    <div className="text-left">
                       <p className="font-bold text-sm text-slate-900">Premium Report</p>
                       <p className="text-[11px] text-slate-500 uppercase tracking-wide">{vehicle.make} {vehicle.model}</p>
                    </div>
                 </div>
                 <span className="font-bold text-slate-900 text-lg">$1.00</span>
              </div>

              <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); handlePayment(); }}>
                 <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5 ml-1">Card Number</label>
                    <div className="relative group">
                       <input 
                         type="text" 
                         value="4242 4242 4242 4242" 
                         readOnly
                         className="w-full border-slate-300 rounded-lg pl-10 py-3 text-sm font-mono text-slate-600 bg-slate-50 focus:ring-0 cursor-not-allowed opacity-70" 
                       />
                       <CreditCard className="absolute left-3 top-3 h-5 w-5 text-slate-400" />
                    </div>
                 </div>
                 <div className="grid grid-cols-2 gap-4">
                    <div>
                       <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5 ml-1">Expiry</label>
                       <input 
                         type="text" 
                         value="12 / 28" 
                         readOnly 
                         className="w-full border-slate-300 rounded-lg py-3 text-sm px-3 font-mono text-slate-600 bg-slate-50 focus:ring-0 cursor-not-allowed opacity-70" 
                        />
                    </div>
                    <div>
                       <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5 ml-1">CVC</label>
                       <input 
                         type="text" 
                         value="123" 
                         readOnly 
                         className="w-full border-slate-300 rounded-lg py-3 text-sm px-3 font-mono text-slate-600 bg-slate-50 focus:ring-0 cursor-not-allowed opacity-70" 
                        />
                    </div>
                 </div>
                 
                 <div className="pt-2">
                    <button 
                      type="submit" 
                      disabled={isProcessing}
                      className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-3.5 rounded-xl flex items-center justify-center gap-2 transition disabled:bg-slate-400 disabled:cursor-wait shadow-lg active:scale-[0.98]"
                    >
                      {isProcessing ? (
                        <>
                          <Loader2 className="h-5 w-5 animate-spin" /> Processing Payment...
                        </>
                      ) : (
                        `Pay $1.00 & Unlock`
                      )}
                    </button>
                    <p className="text-center text-[10px] text-slate-400 mt-3 flex justify-center items-center gap-1">
                       <ShieldCheck className="h-3 w-3" /> Payments processed securely. This is a demo.
                    </p>
                 </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const ListItem = ({ text }: { text: string }) => (
  <li className="flex items-start gap-3">
    <div className="bg-green-100 text-green-600 rounded-full p-0.5 mt-0.5">
       <Check className="h-3 w-3" />
    </div>
    <span className="text-sm text-slate-700 font-medium">{text}</span>
  </li>
);

export default Report;