import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import { Link } from 'react-router-dom';
import { FileText, Download, Check, ShieldCheck, Lock, Zap, CreditCard } from 'lucide-react';
import { Vehicle } from '../types';

interface Props {
  vehicle: Vehicle;
}

const Report: React.FC<Props> = ({ vehicle }) => {
  const [isUnlocked, setIsUnlocked] = useState(false);

  useEffect(() => {
    // Check if user has purchased premium
    const unlocked = localStorage.getItem('fuse_premium_unlocked') === 'true';
    setIsUnlocked(unlocked);
  }, []);

  const generatePDF = () => {
    const doc = new jsPDF();
    const vStr = vehicle.make ? `${vehicle.year} ${vehicle.make} ${vehicle.model}` : 'Unknown Vehicle';
    const dateStr = new Date().toLocaleDateString();
    
    // Header
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Vehicle Health Report", 20, 25);
    doc.setFontSize(10);
    doc.text("Generated by Fuse Finder Pro", 150, 25);

    // Vehicle Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Vehicle Information", 20, 60);
    doc.line(20, 62, 190, 62);
    
    doc.setFontSize(12);
    doc.text(`Vehicle: ${vStr}`, 20, 75);
    doc.text(`Date: ${dateStr}`, 20, 85);
    doc.text(`Report ID: #${Math.floor(Math.random() * 100000)}`, 140, 75);

    // Diagnostics Summary Placeholder
    doc.setFontSize(14);
    doc.text("Diagnostics Summary", 20, 110);
    doc.line(20, 112, 190, 112);
    
    doc.setFontSize(11);
    doc.text("• Fuse System: No active faults detected in lookup history.", 25, 125);
    doc.text("• Maintenance: Schedule generated based on mileage.", 25, 135);
    doc.text("• Visual Inspection: Tire and Oil analysis data included.", 25, 145);

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is generated by AI based on user inputs. Consult a professional mechanic.", 20, 280);

    doc.save("vehicle-health-report.pdf");
  };

  if (!vehicle.make) {
    return (
        <div className="flex flex-col items-center justify-center py-20 text-center px-4">
            <div className="bg-slate-100 p-6 rounded-full mb-4">
                <FileText className="h-10 w-10 text-slate-400" />
            </div>
            <h2 className="text-xl font-bold text-slate-700">No Vehicle Selected</h2>
            <p className="text-slate-500 mt-2 max-w-sm">Please return Home to select a vehicle before generating a report.</p>
        </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      {/* Header */}
      <div className="text-center mb-10">
         <h1 className="text-3xl font-bold text-slate-900">Vehicle Health Report</h1>
         <p className="text-slate-600 mt-2 max-w-2xl mx-auto">
            Comprehensive diagnostics, maintenance schedules, and system analysis for your <strong>{vehicle.year} {vehicle.make} {vehicle.model}</strong>.
         </p>
      </div>

      <div className="grid md:grid-cols-2 gap-8 items-stretch">
        {/* Preview / Benefits Column */}
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 flex flex-col">
           <h2 className="font-bold text-xl mb-6 flex items-center gap-2 text-slate-800">
             <FileText className="h-6 w-6 text-blue-600" /> What's Included
           </h2>
           <ul className="space-y-4 flex-grow">
             <ListItem text="Tire Health Analysis & Tread Life Estimate" />
             <ListItem text="Engine Oil Condition Assessment" />
             <ListItem text="Dashboard Warning Light History" />
             <ListItem text="OEM Recommended Maintenance Schedule" />
             <ListItem text="Fuse Box Diagrams & Location Data" />
           </ul>
           
           <div className="mt-8 bg-slate-50 p-4 rounded-xl border border-slate-200 flex items-center gap-4">
               <div className="bg-white p-3 rounded-lg shadow-sm border border-slate-100">
                  <div className="text-red-500 font-bold text-[10px] leading-none mb-1">PDF</div>
                  <FileText className="h-8 w-8 text-slate-700" />
               </div>
               <div>
                  <p className="font-bold text-slate-800 text-sm">Full_Diagnostic_Report.pdf</p>
                  <p className="text-xs text-slate-500">Includes high-res images & charts</p>
               </div>
           </div>
        </div>

        {/* Action Column */}
        <div className={`bg-white p-8 rounded-2xl shadow-lg border ${isUnlocked ? 'border-green-100' : 'border-blue-100'} relative overflow-hidden flex flex-col justify-center`}>
             
             {isUnlocked ? (
                // Unlocked View
                <div className="text-center animate-fade-in h-full flex flex-col justify-center">
                    <div className="bg-green-50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 border border-green-100">
                       <Check className="h-10 w-10 text-green-600" />
                    </div>
                    <h3 className="text-2xl font-bold text-slate-900 mb-2">Report Ready</h3>
                    <p className="text-slate-600 mb-8 text-sm">
                      Your premium vehicle analysis is ready for download.
                    </p>
                    
                    <button 
                      onClick={generatePDF}
                      className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-4 rounded-xl transition shadow-lg flex items-center justify-center gap-2 group"
                    >
                      <Download className="h-5 w-5 group-hover:scale-110 transition" />
                      Download PDF
                    </button>
                    
                    <p className="mt-6 text-[10px] text-slate-400 flex items-center justify-center gap-1">
                       <ShieldCheck className="h-3 w-3" /> Securely generated on your device
                    </p>
                </div>
             ) : (
                // Locked View (Premium Gate)
                <div className="text-center animate-fade-in relative z-10 h-full flex flex-col justify-center">
                    <div className="bg-blue-50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 border border-blue-100">
                       <Lock className="h-8 w-8 text-blue-600" />
                    </div>
                    <h3 className="text-2xl font-bold text-slate-900 mb-2">Unlock Premium Report</h3>
                    <p className="text-slate-600 mb-6 text-sm">
                      Get the detailed AI diagnostics, full fuse diagrams, and personalized maintenance steps.
                    </p>
                    <div className="text-3xl font-extrabold text-slate-900 mb-6">
                        $4.99 <span className="text-sm font-normal text-slate-500">/ one-time</span>
                    </div>
                    
                    {/* Mock Stripe Link -> Goes to Success Page for Demo */}
                    <Link 
                      to="/success"
                      className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-xl transition shadow-lg flex items-center justify-center gap-2 group mb-4"
                    >
                      <CreditCard className="h-5 w-5" />
                      Unlock Now
                    </Link>
                    <p className="text-xs text-slate-400 flex items-center justify-center gap-1">
                      <ShieldCheck className="h-3 w-3" /> Secure Payment via Stripe
                    </p>
                </div>
             )}
        </div>
      </div>
    </div>
  );
};

const ListItem = ({ text }: { text: string }) => (
  <li className="flex items-start gap-3">
    <div className="bg-green-100 text-green-600 rounded-full p-0.5 mt-0.5">
       <Check className="h-3 w-3" />
    </div>
    <span className="text-sm text-slate-700 font-medium">{text}</span>
  </li>
);

export default Report;